"""Teleportation Protocol Implementation
    This module implements the teleportation protocol for quantum communication.
    It includes the core logic for Alice's and Bob's sides of the teleportation process,
    handling entangled states, and applying corrections based on classical messages.
"""

from enum import Enum, auto

from sequence.components.circuit import Circuit
from sequence.components.memory import Memory
from sequence.message import Message
from sequence.utils import log
from sequence.protocol import Protocol
from sequence.network_management.reservation import Reservation


class HetTeleportMsgType(Enum):
    """Enumeration for different types of teleportation messages."""
    MEASUREMENT_RESULT = auto() # Alice informs Bob of her measurement result
    ACK = auto()                # Bob acknowledges Alice the teleportation is complete


class HetTeleportMessage(Message):
    """Classical message used to convey the Pauli corrections (x, z) from
    sender to receiver during teleportation.

    Attributes:
        reservation (Reservation): The reservation object associated with this teleportation message.
        bob_comm_memory_name (str): Name of the memory on Bob's side to be corrected.
        x_flip (int): MEASUREMENT_RESULT only, whether to apply X correction (1 for yes, 0 for no).
        z_flip (int): MEASUREMENT_RESULT only, whether to apply Z correction (1 for yes, 0 for no).
    """
    def __init__(self, msg_type: HetTeleportMsgType, **kwargs):
        # HetQR routes messages to a named protocol rather than a teleport_app receiver.
        super().__init__(msg_type, kwargs['receiver'])

        if msg_type is HetTeleportMsgType.MEASUREMENT_RESULT:
            self.reservation = kwargs['reservation']
            self.bob_comm_memory_name = kwargs['bob_comm_memory_name']
            self.bob_data_memory_index = kwargs['bob_data_memory_index']
            self.alice_protocol_name = kwargs['alice_protocol_name']
            self.x_flip = kwargs['x_flip']
            self.z_flip = kwargs['z_flip']
            self.string = f'type={HetTeleportMsgType.MEASUREMENT_RESULT}, bob_comm_memory={self.bob_comm_memory_name}, x_flip={self.x_flip}, z_flip={self.z_flip}, reservation={self.reservation}'

        elif msg_type is HetTeleportMsgType.ACK:
            self.reservation = kwargs['reservation']
            self.bob_comm_memory_name = kwargs['bob_comm_memory_name']
            self.string = f'type={HetTeleportMsgType.ACK}, bob_comm_memory={self.bob_comm_memory_name}, reservation={self.reservation}'

        else:
            raise Exception(f"HetTeleportMessage created with unknown message type: {msg_type}")

    def __str__(self):
        return self.string


class HetTeleportProtocol(Protocol):
    """Core teleportation logic:
     - handle_entangled(): invoked when a comm-memory becomes ENTANGLED
     - handle_correction(): invoked when Bob receives Alice's classical bits

    NOTE: the teleport protocol is not generated by the Rule system
           Can it be? Seems pretty hard to be generated by the Rule system
    NOTE: this protocol is asymmetric, alice and bob behave very differently

    Attributes:
        owner: The node that owns this protocol.
        data_memory (str): The name of the data memory to teleport on Alice's side.
        alice (bool): Whether this protocol plays the Alice role.
        name (str): The name of the teleport protocol.
        remote_node_name (str): The name of the remote node (Bob) involved in the teleportation.
        alice_comm_memory_name (str): The name of the communication memory on Alice's side.
        alice_comm_memory (Memory): The communication memory on Alice's side.
        bob_comm_memory_name (str): The name of the communication memory on Bob's side.
        bob_comm_memory (Memory): The communication memory on Bob's side.
    """

    _bsm_circuit = Circuit(2)
    _bsm_circuit.cx(0,1)
    _bsm_circuit.h(0)
    _bsm_circuit.measure(0)
    _bsm_circuit.measure(1)

    _z_flip_circuit = Circuit(1)
    _z_flip_circuit.z(0)

    _x_flip_circuit = Circuit(1)
    _x_flip_circuit.x(0)

    # Heterogeneous extension: move the corrected state into Bob's data memory.
    _swap_circuit = Circuit(2)
    _swap_circuit.swap(0,1)

    def __init__(self, owner,  alice: bool = False, data_memory_index: int = None, remote_node_name: str = None, bob_data_memory_index: int = 0):
        """ Initialize the teleportation protocol.

        Args:
            owner: Node that owns this protocol.
            alice (bool): Whether this protocol plays the Alice role.
            data_memory_index (int): The index of the data memory to teleport.
            remote_node_name (str): The name of the other node involved in the teleportation.
            bob_data_memory_index (int): Index of Bob's destination data memory.
        """
        self.owner = owner
        self.alice = alice
        self.data_memory_index = data_memory_index
        self.remote_node_name = remote_node_name
        self.bob_data_memory_index = bob_data_memory_index
        if self.alice:
            self.name = f"{owner.name}.teleport.{remote_node_name}.DataMemoryArray[{data_memory_index}]"
        else:
            self.name = f"{owner.name}.teleport.{remote_node_name}"
        self.alice_comm_memory_name: str = None     # To be decided after the entangle pair is generated
        self.alice_comm_memory: Memory = None
        self.bob_comm_memory_name: str = None       # To be decided after the entangle pair is generated
        self.bob_comm_memory: Memory = None
        log.logger.debug(f"{self.name}: initialized (data_memory={data_memory_index})")

    def set_alice_comm_memory_name(self, memory_name: str):
        """Set the communication memory for Alice.

        Args:
            memory_name (str): The name of the communication memory.
        """
        self.alice_comm_memory_name = memory_name

    def set_alice_comm_memory(self, memory: Memory):
        """Set the communication memory for Alice.

        Args:
            memory (Memory): The communication memory.
        """
        self.alice_comm_memory = memory

    def set_bob_comm_memory_name(self, memory_name: str):
        """Set the communication memory for Bob.

        Args:
            memory_name (str): The name of the communication memory.
        """
        self.bob_comm_memory_name = memory_name

    def set_bob_comm_memory(self, memory: Memory):
        """Set the communication memory for Bob.

        Args:
            memory (Memory): The communication memory.
        """
        self.bob_comm_memory = memory

    @staticmethod
    def protocol_name(owner_name: str, remote_node_name: str, memory_name: str) -> str:
        """Return the deterministic name required by HetQR message routing."""
        return f"{owner_name}.HetTeleportProtocol.{remote_node_name}.{memory_name}"

    def set_name_for_comm_memory(self):
        """Set the routable protocol name once its local comm memory is known."""
        memory_name = self.alice_comm_memory_name if self.alice else self.bob_comm_memory_name
        self.name = self.protocol_name(self.owner.name, self.remote_node_name, memory_name)

    def alice_bell_measurement(self, reservation: Reservation):
        """ Perform Bell measurement on the entangled memory and send corrections to Bob.
        """
        comm_key = self.alice_comm_memory.qstate_key
        data_memory = self.owner.app.get_data_memory(self.data_memory_index)
        data_key = data_memory.qstate_key
        log.logger.debug(f"{self.name}: alice_bell_measure data_key={data_key}, comm_key={comm_key}")
        # Perform Bell measurement
        rnd  = self.owner.get_generator().random()
        meas = self.owner.timeline.quantum_manager.run_circuit(HetTeleportProtocol._bsm_circuit, [data_key, comm_key], rnd)
        z, x = meas[data_key], meas[comm_key]
        log.logger.info(f"{self.name} bell measurement results: x={x}, z={z}, remote memory={self.bob_comm_memory_name}")
        # send classical corrections to Bob
        receiver = self.protocol_name(self.remote_node_name, self.owner.name, self.bob_comm_memory_name)
        msg = HetTeleportMessage(HetTeleportMsgType.MEASUREMENT_RESULT, receiver=receiver, bob_comm_memory_name=self.bob_comm_memory_name, bob_data_memory_index=self.bob_data_memory_index, alice_protocol_name=self.name, x_flip=x, z_flip=z, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)

    def received_message(self, src: str, msg: HetTeleportMessage):
        """ Handle incoming messages, specifically teleportation corrections.

        Args:
            src (str): Source of the message.
            msg (HetTeleportMessage): The teleportation message containing corrections.
        """
        if msg.msg_type == HetTeleportMsgType.MEASUREMENT_RESULT:
            self.bob_handle_correction(msg)
        elif msg.msg_type == HetTeleportMsgType.ACK:
            self.owner.app.alice_protocol_complete(self, msg.reservation)
        else:
            log.logger.warning(f"{self.name}: received unknown message type {msg.type} from {src}")

    def bob_handle_correction(self, msg: HetTeleportMessage):
        """ Handle the classical correction message from Alice.
        Applies the corrections to the entangled memory and notifies the app.

        Args:
            msg (HetTeleportMessage): The message containing the correction bits.
        """
        log.logger.debug(f"{self.name}: bob_handle_correction, memory={msg.bob_comm_memory_name}, x_flip={msg.x_flip}, z_flip={msg.z_flip}")
        bob_comm_memory_key = self.bob_comm_memory.qstate_key

        # Heterogeneous extension: |Psi+> adds an X to the standard |Phi+> table.
        if msg.x_flip ^ 1:
            rnd = self.owner.get_generator().random()
            self.owner.timeline.quantum_manager.run_circuit(HetTeleportProtocol._x_flip_circuit, [bob_comm_memory_key], rnd)
            log.logger.info(f"{self.name}: X-flip applied on memory {msg.bob_comm_memory_name}")
        if msg.z_flip:
            rnd = self.owner.get_generator().random()
            self.owner.timeline.quantum_manager.run_circuit(HetTeleportProtocol._z_flip_circuit, [bob_comm_memory_key], rnd)
            log.logger.info(f"{self.name}: Z-flip applied on memory {msg.bob_comm_memory_name}")

        # Heterogeneous extension: SWAP corrected comm memory into data memory.
        data_memory = self.owner.app.get_data_memory(msg.bob_data_memory_index)
        bob_data_memory_key = data_memory.qstate_key
        if bob_comm_memory_key == bob_data_memory_key:
            raise ValueError("Data and communication memories must be different qubits")
        rnd = self.owner.get_generator().random()
        self.owner.timeline.quantum_manager.run_circuit(HetTeleportProtocol._swap_circuit, [bob_comm_memory_key, bob_data_memory_key], rnd)

        self.owner.app.teleport_complete(bob_data_memory_key)
        self.owner.app.bob_protocol_complete(self, msg)

    def bob_acknowledge_complete(self, msg: HetTeleportMessage):
        """Acknowledge the completion of the teleportation process.

        Args:
            msg (HetTeleportMessage): Alice's measurement-result message.
        """
        ack = HetTeleportMessage(HetTeleportMsgType.ACK, receiver=msg.alice_protocol_name, bob_comm_memory_name=self.bob_comm_memory_name, reservation=msg.reservation)
        self.owner.send_message(self.remote_node_name, ack)
        log.logger.debug(f"{self.name}: sent ACK to {self.remote_node_name}")
